<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\CommercialRoute;

class CommercialRoutesSeeder extends Seeder
{
    public function run()
    {
        $routes = [
            // OPTION 1
            [
                'option' => 'OPTION 1',
                'name_of_route' => 'Riverside Mews-Ring Road*',
                'no_of_cores_required' => 1,
                'unit_cost_per_core_per_km_per_month' => 20,
                'approx_distance_km' => 2.5,
                'capital_expenditure' => 450000,
                'availability' => 'NO',
                'currency' => 'KES',
                'tech_type' => 'ADSS',
            ],
            [
                'option' => 'OPTION 1',
                'name_of_route' => 'Ring Road - Westlands substation',
                'no_of_cores_required' => 1,
                'unit_cost_per_core_per_km_per_month' => 20,
                'approx_distance_km' => 3,
                'capital_expenditure' => 0,
                'availability' => 'YES',
                'currency' => 'USD',
                'tech_type' => 'ADSS',
            ],
            [
                'option' => 'OPTION 1',
                'name_of_route' => 'Westlands substation - Parklands substation',
                'no_of_cores_required' => 1,
                'unit_cost_per_core_per_km_per_month' => 20,
                'approx_distance_km' => 5,
                'capital_expenditure' => 0,
                'availability' => 'YES',
                'currency' => 'USD',
                'tech_type' => 'ADSS',
            ],
            [
                'option' => 'OPTION 1',
                'name_of_route' => 'Parklands substation - Roysambu Substation',
                'no_of_cores_required' => 1,
                'unit_cost_per_core_per_km_per_month' => 20,
                'approx_distance_km' => 12,
                'capital_expenditure' => 0,
                'availability' => 'YES',
                'currency' => 'USD',
                'tech_type' => 'ADSS',
            ],
            [
                'option' => 'OPTION 1',
                'name_of_route' => 'Roysambu Substation - NCC-Dandora-Embakasi substation',
                'no_of_cores_required' => 1,
                'unit_cost_per_core_per_km_per_month' => 20,
                'approx_distance_km' => 23.8, // 7.5+1.8+14.5
                'capital_expenditure' => 0,
                'availability' => 'YES',
                'currency' => 'USD',
                'tech_type' => 'OPGW',
            ],
            [
                'option' => 'OPTION 1',
                'name_of_route' => 'Embakasi substation - Villa Franca substation',
                'no_of_cores_required' => 1,
                'unit_cost_per_core_per_km_per_month' => 20,
                'approx_distance_km' => 3,
                'capital_expenditure' => 0,
                'availability' => 'YES',
                'currency' => 'USD',
                'tech_type' => 'ADSS',
            ],
            [
                'option' => 'OPTION 1',
                'name_of_route' => 'Villa Franca substation - IX Africa Data Center*',
                'no_of_cores_required' => 1,
                'unit_cost_per_core_per_km_per_month' => 20,
                'approx_distance_km' => 2.5,
                'capital_expenditure' => 0,
                'availability' => 'YES',
                'currency' => 'USD',
                'tech_type' => 'ADSS',
            ],

            // OPTION 2
            [
                'option' => 'OPTION 2',
                'name_of_route' => 'Riverside Mews-Ring Road*',
                'no_of_cores_required' => 1,
                'unit_cost_per_core_per_km_per_month' => 20,
                'approx_distance_km' => 2.5,
                'capital_expenditure' => 450000,
                'availability' => 'NO',
                'currency' => 'USD',
                'tech_type' => 'ADSS',
            ],
            [
                'option' => 'OPTION 2',
                'name_of_route' => 'Ring Road - Kileleshwa substation',
                'no_of_cores_required' => 1,
                'unit_cost_per_core_per_km_per_month' => 20,
                'approx_distance_km' => 2.5,
                'capital_expenditure' => 0,
                'availability' => 'YES',
                'currency' => 'USD',
                'tech_type' => 'ADSS',
            ],
            [
                'option' => 'OPTION 2',
                'name_of_route' => 'Kileleshwa substation - Ngong Road substation',
                'no_of_cores_required' => 1,
                'unit_cost_per_core_per_km_per_month' => 20,
                'approx_distance_km' => 4,
                'capital_expenditure' => 0,
                'availability' => 'YES',
                'currency' => 'USD',
                'tech_type' => 'ADSS',
            ],
            [
                'option' => 'OPTION 2',
                'name_of_route' => 'Ngong Road substation - Ragati ss - City Center Substation',
                'no_of_cores_required' => 1,
                'unit_cost_per_core_per_km_per_month' => 20,
                'approx_distance_km' => 4.85, // 2+2.85
                'capital_expenditure' => 0,
                'availability' => 'YES',
                'currency' => 'USD',
                'tech_type' => 'ADSS',
            ],
            [
                'option' => 'OPTION 2',
                'name_of_route' => 'City Center Substation - Embakasi substation',
                'no_of_cores_required' => 1,
                'unit_cost_per_core_per_km_per_month' => 20,
                'approx_distance_km' => 16,
                'capital_expenditure' => 0,
                'availability' => 'YES',
                'currency' => 'USD',
                'tech_type' => 'UG',
            ],
            [
                'option' => 'OPTION 2',
                'name_of_route' => 'Embakasi substation - Villa Franca substation',
                'no_of_cores_required' => 1,
                'unit_cost_per_core_per_km_per_month' => 20,
                'approx_distance_km' => 3,
                'capital_expenditure' => 0,
                'availability' => 'YES',
                'currency' => 'USD',
                'tech_type' => 'ADSS',
            ],
            [
                'option' => 'OPTION 2',
                'name_of_route' => 'Villa Franca substation - IX Africa Data Center*',
                'no_of_cores_required' => 1,
                'unit_cost_per_core_per_km_per_month' => 20,
                'approx_distance_km' => 2.5,
                'capital_expenditure' => 0,
                'availability' => 'YES',
                'currency' => 'USD',
                'tech_type' => 'ADSS',
            ],

            // OPTION 3
            [
                'option' => 'OPTION 3',
                'name_of_route' => 'Riverside Mews-Ring Road*',
                'no_of_cores_required' => 1,
                'unit_cost_per_core_per_km_per_month' => 20,
                'approx_distance_km' => 2.5,
                'capital_expenditure' => 450000,
                'availability' => 'NO',
                'currency' => 'USD',
                'tech_type' => 'ADSS',
            ],
            [
                'option' => 'OPTION 3',
                'name_of_route' => 'Ring Road - Kileleshwa substation',
                'no_of_cores_required' => 1,
                'unit_cost_per_core_per_km_per_month' => 20,
                'approx_distance_km' => 2.5,
                'capital_expenditure' => 0,
                'availability' => 'YES',
                'currency' => 'USD',
                'tech_type' => 'ADSS',
            ],
            [
                'option' => 'OPTION 3',
                'name_of_route' => 'Kileleshwa substation - Ngong Road substation',
                'no_of_cores_required' => 1,
                'unit_cost_per_core_per_km_per_month' => 20,
                'approx_distance_km' => 4,
                'capital_expenditure' => 0,
                'availability' => 'YES',
                'currency' => 'USD',
                'tech_type' => 'ADSS',
            ],
            [
                'option' => 'OPTION 3',
                'name_of_route' => 'Ngong Road substation-Nairobi West substation',
                'no_of_cores_required' => 1,
                'unit_cost_per_core_per_km_per_month' => 20,
                'approx_distance_km' => 5,
                'capital_expenditure' => 0,
                'availability' => 'YES',
                'currency' => 'USD',
                'tech_type' => 'ADSS',
            ],
            [
                'option' => 'OPTION 3',
                'name_of_route' => 'Nairobi West substation - Embakasi substation',
                'no_of_cores_required' => 1,
                'unit_cost_per_core_per_km_per_month' => 20,
                'approx_distance_km' => 13,
                'capital_expenditure' => 0,
                'availability' => 'YES',
                'currency' => 'USD',
                'tech_type' => 'ADSS',
            ],
            [
                'option' => 'OPTION 3',
                'name_of_route' => 'Embakasi substation - Villa Franca substation',
                'no_of_cores_required' => 1,
                'unit_cost_per_core_per_km_per_month' => 20,
                'approx_distance_km' => 3,
                'capital_expenditure' => 0,
                'availability' => 'YES',
                'currency' => 'USD',
                'tech_type' => 'ADSS',
            ],
            [
                'option' => 'OPTION 3',
                'name_of_route' => 'Villa Franca substation - IX Africa Data Center*',
                'no_of_cores_required' => 1,
                'unit_cost_per_core_per_km_per_month' => 20,
                'approx_distance_km' => 2.5,
                'capital_expenditure' => 0,
                'availability' => 'YES',
                'currency' => 'USD',
                'tech_type' => 'ADSS',
            ],
        ];

        foreach ($routes as $routeData) {
            CommercialRoute::create($routeData);
        }
    }
}
